version: '3.3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    ports:
      - 8001:5000
    extra_hosts:
      - "docker.for.linux.localhost:$DOCKERHOST"
    volumes:
      - .:/app
    depends_on:
      - db
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
    depends_on:
      - db
  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33067:3306
    extra_hosts:
      - "docker.for.linux.localhost:$DOCKERHOST"







